<?xml version="1.0" encoding="utf-8"?><Database Name="gringlobal" Class="RepositoryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ARSMDBE33DB1;Initial Catalog=gringlobal;Integrated Security=True" SettingsObjectName="USDA.ARS.GRIN.Web.Repository.Properties.Settings" SettingsPropertyName="gringlobalConnectionString4" Provider="System.Data.SqlClient" />
  <Function Name="dbo.LP_SEARCH_RHIZOBIUM" Method="LP_SEARCH_RHIZOBIUM">
    <Parameter Name="searchString" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="LP_SEARCH_RHIZOBIUMResult">
      <Column Name="rhy_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="identifier" Type="System.String" DbType="NVarChar(243)" CanBeNull="true" />
      <Column Name="usda_acces" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="synonym_1" Type="System.String" DbType="NVarChar(26)" CanBeNull="true" />
      <Column Name="synonym_2" Type="System.String" DbType="NVarChar(243)" CanBeNull="true" />
      <Column Name="synonym_3" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="synonym_4" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="host_plant" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="common_nam" Type="System.String" DbType="NVarChar(29)" CanBeNull="true" />
      <Column Name="source" Type="System.String" DbType="NVarChar(39)" CanBeNull="true" />
      <Column Name="geo_source" Type="System.String" DbType="NVarChar(47)" CanBeNull="true" />
      <Column Name="serogroup" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="hosts_nodu" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="comments" Type="System.String" DbType="NVarChar(71)" CanBeNull="true" />
      <Column Name="genus_spp" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LP_SEARCH_RHYZOBIUM" Method="LP_SEARCH_RHYZOBIUM">
    <Parameter Name="searchString" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="LP_SEARCH_RHYZOBIUMResult">
      <Column Name="rhy_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="identifier" Type="System.String" DbType="NVarChar(243)" CanBeNull="true" />
      <Column Name="usda_acces" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="synonym_1" Type="System.String" DbType="NVarChar(26)" CanBeNull="true" />
      <Column Name="synonym_2" Type="System.String" DbType="NVarChar(243)" CanBeNull="true" />
      <Column Name="synonym_3" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="synonym_4" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="host_plant" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="common_nam" Type="System.String" DbType="NVarChar(29)" CanBeNull="true" />
      <Column Name="source" Type="System.String" DbType="NVarChar(39)" CanBeNull="true" />
      <Column Name="geo_source" Type="System.String" DbType="NVarChar(47)" CanBeNull="true" />
      <Column Name="serogroup" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="hosts_nodu" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="comments" Type="System.String" DbType="NVarChar(71)" CanBeNull="true" />
      <Column Name="genus_spp" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LP_RHIZOBIUM_SEARCH" Method="LP_RHIZOBIUM_SEARCH">
    <Parameter Name="searchString" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="LP_RHIZOBIUM_SEARCHResult">
      <Column Name="rhy_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="identifier" Type="System.String" DbType="NVarChar(243)" CanBeNull="true" />
      <Column Name="usda_acces" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="synonym_1" Type="System.String" DbType="NVarChar(26)" CanBeNull="true" />
      <Column Name="synonym_2" Type="System.String" DbType="NVarChar(243)" CanBeNull="true" />
      <Column Name="synonym_3" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="synonym_4" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="host_plant" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="common_nam" Type="System.String" DbType="NVarChar(29)" CanBeNull="true" />
      <Column Name="source" Type="System.String" DbType="NVarChar(39)" CanBeNull="true" />
      <Column Name="geo_source" Type="System.String" DbType="NVarChar(47)" CanBeNull="true" />
      <Column Name="serogroup" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="hosts_nodu" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="comments" Type="System.String" DbType="NVarChar(71)" CanBeNull="true" />
      <Column Name="genus_spp" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LP_RHIZOBIUM_GET_HOST_PLANT_LIST" Method="LP_RHIZOBIUM_GET_HOST_PLANT_LIST">
    <ElementType Name="LP_RHIZOBIUM_GET_HOST_PLANT_LISTResult">
      <Column Name="host_plant" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LP_RHIZOBIUM_GET_DETAIL" Method="LP_RHIZOBIUM_GET_DETAIL">
    <Parameter Name="host_plant_name" Type="System.String" DbType="NVarChar(254)" />
    <ElementType Name="LP_RHIZOBIUM_GET_DETAILResult">
      <Column Name="rhy_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="identifier" Type="System.String" DbType="NVarChar(243)" CanBeNull="true" />
      <Column Name="usda_acces" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="synonym_1" Type="System.String" DbType="NVarChar(26)" CanBeNull="true" />
      <Column Name="synonym_2" Type="System.String" DbType="NVarChar(243)" CanBeNull="true" />
      <Column Name="synonym_3" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="synonym_4" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="host_plant" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="common_nam" Type="System.String" DbType="NVarChar(29)" CanBeNull="true" />
      <Column Name="source" Type="System.String" DbType="NVarChar(39)" CanBeNull="true" />
      <Column Name="geo_source" Type="System.String" DbType="NVarChar(47)" CanBeNull="true" />
      <Column Name="serogroup" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="hosts_nodu" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="comments" Type="System.String" DbType="NVarChar(71)" CanBeNull="true" />
      <Column Name="genus_spp" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_GetCropsBySite" Method="usp_GetCropsBySite">
    <ElementType Name="usp_GetCropsBySiteResult">
      <Column Name="site_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="site_long_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="crop_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STATE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="owned_by" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_User_Search" Method="usp_User_Search">
    <Parameter Name="user_name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="usp_User_SearchResult">
      <Column Name="sys_user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="organization" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="organization_abbrev" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="address_line1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="address_line2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="address_line3" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="geography_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="primary_phone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="job" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="postal_index" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="is_enabled" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="cooperator_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="created_by" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="modified_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="owned_date" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="owned_by" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sys_lang_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="site_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="site_short_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="site_long_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_PVPRecentApplications_Select" Method="usp_ARS_PVPRecentApplications_Select">
    <ElementType Name="usp_ARS_PVPRecentApplications_SelectResult">
      <Column Name="pvp_application_number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cultivar_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="experimental_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="pvp_common_name_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="common_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="scientific_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="pvp_applicant_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="applicant_name" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="application_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="is_certified_seed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="pvp_application_status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="application_status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="certificate_issued_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="years_protected" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="accession_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="expiration_date" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_PVPRecentlyAvailable_Select" Method="usp_ARS_PVPRecentlyAvailable_Select">
    <ElementType Name="usp_ARS_PVPRecentlyAvailable_SelectResult">
      <Column Name="pvp_application_number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cultivar_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="experimental_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="pvp_common_name_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="common_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="scientific_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="pvp_applicant_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="applicant_name" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="application_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="is_certified_seed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="pvp_application_status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="application_status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="certificate_issued_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="years_protected" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="accession_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="expiration_date" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_PVPRecentlyExpired_Select" Method="usp_ARS_PVPRecentlyExpired_Select">
    <ElementType Name="usp_ARS_PVPRecentlyExpired_SelectResult">
      <Column Name="pvp_application_number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cultivar_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="experimental_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="pvp_common_name_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="common_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="scientific_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="pvp_applicant_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="applicant_name" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="application_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="is_certified_seed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="pvp_application_status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="application_status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="certificate_issued_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="years_protected" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="accession_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="expiration_date" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_PVPExpiring6Months_Select" Method="usp_ARS_PVPExpiring6Months_Select">
    <ElementType Name="usp_ARS_PVPExpiring6Months_SelectResult">
      <Column Name="pvp_application_number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cultivar_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="experimental_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="pvp_common_name_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="common_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="scientific_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="pvp_applicant_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="applicant_name" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="application_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="is_certified_seed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="pvp_application_status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="application_status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="certificate_issued_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="years_protected" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="accession_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="expiration_date" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_CodesByGroup_Select" Method="usp_CodesByGroup_Select">
    <Parameter Name="group_name" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="usp_CodesByGroup_SelectResult">
      <Column Name="code_value_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="code_value_lang_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="group_name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_CropGermplasmCommittee_Select" Method="usp_ARS_CropGermplasmCommittee_Select">
    <Parameter Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_ARS_CropGermplasmCommittee_SelectResult">
      <Column Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crop_germplasm_committee_name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="roster_url" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="created_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="modified_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_CropGermplasmCommitteeApplicationStatuses_Select" Method="usp_ARS_CropGermplasmCommitteeApplicationStatuses_Select">
    <ElementType Name="usp_ARS_CropGermplasmCommitteeApplicationStatuses_SelectResult">
      <Column Name="status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_CropGermplasmCommittees_Select" Method="usp_ARS_CropGermplasmCommittees_Select">
    <ElementType Name="usp_ARS_CropGermplasmCommittees_SelectResult">
      <Column Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crop_germplasm_committee_name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="roster_url" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="created_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="modified_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_CropGermplasmCommitteeCropDescriptors_Select" Method="usp_ARS_CropGermplasmCommitteeCropDescriptors_Select">
    <Parameter Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_ARS_CropGermplasmCommitteeCropDescriptors_SelectResult">
      <Column Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crop_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_PVPApplications_Search" Method="usp_ARS_PVPApplications_Search">
    <Parameter Name="sql_where_clause" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="usp_ARS_PVPApplications_SearchResult">
      <Column Name="pvp_application_number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cultivar_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="experimental_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="pvp_crop_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="scientific_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="common_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="pvp_applicant_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="applicant_name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="application_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="is_certified_seed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="pvp_application_status_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="application_status" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Column Name="status_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="certificate_issued_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="years_protected" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="expiration_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="months_remaining" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="accession_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_PVPApplicationStatuses_Select" Method="usp_ARS_PVPApplicationStatuses_Select">
    <ElementType Name="usp_ARS_PVPApplicationStatuses_SelectResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="count" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_CropGermplasmCommitteeDocuments_Select" Method="usp_ARS_CropGermplasmCommitteeDocuments_Select">
    <Parameter Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_ARS_CropGermplasmCommitteeDocuments_SelectResult">
      <Column Name="crop_germplasm_committee_name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="crop_germplasm_committee_document_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="document_title" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="category_code" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="document_year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="created_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="modified_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_CropGermplasmCommitteeDocuments_SelectAll" Method="usp_ARS_CropGermplasmCommitteeDocuments_SelectAll">
    <ElementType Name="usp_ARS_CropGermplasmCommitteeDocuments_SelectAllResult">
      <Column Name="crop_germplasm_committee_name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="crop_germplasm_committee_document_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="document_title" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="category_code" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="document_year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="created_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="modified_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_CropGermplasmCommitteeDocumentsRecent_Select" Method="usp_ARS_CropGermplasmCommitteeDocumentsRecent_Select">
    <ElementType Name="usp_ARS_CropGermplasmCommitteeDocumentsRecent_SelectResult">
      <Column Name="crop_germplasm_committee_name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="crop_germplasm_committee_document_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="document_title" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="category_code" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="document_year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="created_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="modified_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_CropGermplasmCommitteeDocument_Delete" Method="usp_ARS_CropGermplasmCommitteeDocument_Delete">
    <Parameter Name="out_error_number" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="crop_germplasm_committee_document_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_ARS_CropGermplasmCommitteeDocument_Insert" Method="usp_ARS_CropGermplasmCommitteeDocument_Insert">
    <Parameter Name="out_error_number" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="out_crop_germplasm_committee_document_id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="title" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="document_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="category_code" Type="System.String" DbType="NVarChar(4)" />
    <Parameter Name="url" Type="System.String" DbType="NVarChar(120)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_ARS_CropGermplasmCommitteeDocument_Update" Method="usp_ARS_CropGermplasmCommitteeDocument_Update">
    <Parameter Name="out_error_number" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="crop_germplasm_committee_document_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="title" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="document_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="category_code" Type="System.String" DbType="NVarChar(4)" />
    <Parameter Name="url" Type="System.String" DbType="NVarChar(120)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_ARS_CropGermplasmCommitteeDocument_Select" Method="usp_ARS_CropGermplasmCommitteeDocument_Select">
    <Parameter Name="crop_germplasm_committee_document_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_ARS_CropGermplasmCommitteeDocument_SelectResult">
      <Column Name="crop_germplasm_committee_name" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="crop_germplasm_committee_document_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crop_germplasm_committee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="document_title" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="category_code" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="document_year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="category_title" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="created_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="modified_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_ARS_PVPApplication_Select" Method="usp_ARS_PVPApplication_Select">
    <Parameter Name="crop_description" Type="System.String" DbType="NVarChar(60)" />
  </Function>
</Database>